acrossx/acrossx.ttl
cmi5/cmi5
scorm/scorm.ttl
seriousgames/seriousgames.ttl
video/video.ttl

added .ttl versions of profiles as RDF

Add .ttl versions

---

cmi5/cmi5.jsonld
cmi5/cmi5.ttl

simplified title to cmi5 profile

simplified title

---

scorm/scorm.jsonld
scorm/scorm.ttl

was missing RDF declaration for type:Profile

Added Profile Type to SCORM Profile

---

acrossx/acrossx.jsonld
acrossx/acrossx.ttl
adb/adb.jsonld
adb/adb.ttl
scorm/scorm.jsonld
scorm/scorm.ttl

typo correction

---

video/video.jsonld
video/video.ttl

description

---

acrossx/acrossx.jsonld
acrossx/acrossx.ttl
adb/adb.jsonld
adb/adb.ttl
seriousgames/seriousgames.jsonld
seriousgames/seriousgames.ttl
video/video.jsonld
video/video.ttl
virtual-patient/virtual-patient.jsonld
virtual-patient/virtual-patient.ttl

Examples were trying to use schema:Group, which isn’t a correct
property. It should be schema:Person or schema:Organization for the
author of the profile.

Corrections to profile author

---

cmi5/cmi5.jsonld
cmi5/cmi5.ttl
scorm/scorm.jsonld
scorm/scorm.ttl
video/video.jsonld
video/video.ttl

Corrections to published profiles. Updated “rule” property to use
“presence” instead based on profile spec. Also added some labels and definitions to templates and patterns.

Corrections to published profiles

---

video/video.jsonld
video/video.ttl

updates to minor errors in the profile

Video Profile Corrections

---

acrossx/acrossx.jsonld
acrossx/acrossx.ttl
adb/adb.ttl
cmi5/cmi5.ttl
scorm/scorm.ttl
seriousgames/seriousgames.ttl
video/video.ttl
virtual-patient/virtual-patient.ttl

Attempt to resolve namespacing conflict with schema namespace used in
xAPI profile @context. JSON-LD does convert to turtle well and .ttl is
what is used to during import into triple store. Also made a few other
minor updates to resolve syntax issues in published profiles.

Update for Namespace Conflict

---

acrossx/acrossx.ttl
adb/adb.ttl
cmi5/cmi5.ttl
scorm/scorm.ttl
seriousgames/seriousgames.ttl
video/video.ttl
virtual-patient/virtual-patient.ttl

Revert schema.org changes

---

acrossx/acrossx.jsonld
acrossx/acrossx.ttl

removed multiple seeAlso references

update to acrossx

---

cmi5/cmi5.jsonld
cmi5/cmi5.ttl

update to versions for cmi5 profile

cmi5 update

---

cmi5/cmi5.ttl

cmi5 - turtle

---

seriousgames/seriousgames.jsonld
seriousgames/seriousgames.ttl

added missing “inScheme” for all concepts

seriousgames

---

activity-streams/activity-streams.jsonld
open-badges/open-badges.jsonld
pdf-annotator/pdf-annotator.jsonld
tincan/tincan.jsonld

Imported concepts and profiles from TinCan Registry

New Imports

---

activity-streams/activity-streams.jsonld
activity-streams/activity-streams.ttl
open-badges/open-badges.ttl
pdf-annotator/pdf-annotator.jsonld
pdf-annotator/pdf-annotator.ttl
tincan/tincan.jsonld
tincan/tincan.ttl

Syntax corrections

---

activity-streams/activity-streams.jsonld
activity-streams/activity-streams.ttl
pdf-annotator/pdf-annotator.jsonld
pdf-annotator/pdf-annotator.ttl

More syntax fixes

---

activity-streams/activity-streams.jsonld
activity-streams/activity-streams.ttl

update to triples

---

activity-streams/activity-streams.jsonld
activity-streams/activity-streams.ttl

activity streams

---

activity-streams/activity-streams.jsonld
activity-streams/activity-streams.ttl

text update

---

pdf-annotator/pdf-annotator.jsonld
pdf-annotator/pdf-annotator.ttl
tincan/tincan.jsonld
tincan/tincan.ttl

typo corrections

---

open-badges/open-badges.jsonld
open-badges/open-badges.ttl
tincan/tincan.jsonld
tincan/tincan.ttl

text updates

---

video/video.jsonld
video/video.ttl

removed ended

---

acrossx/acrossx.jsonld
activity-streams/activity-streams.jsonld
adb/adb.jsonld
adl/adl.jsonld
open-badges/open-badges.jsonld
pdf-annotator/pdf-annotator.jsonld
scorm/scorm.jsonld
seriousgames/seriousgames.jsonld
tincan/tincan.jsonld
video/video.jsonld
virtual-patient/virtual-patient.jsonld

Made sure that the `inScheme` matched the current version id, but was unique to the overall `id`

Fixed errors listed in Issue 35

---

video/v1.2/video.jsonld
video/v1.2/video.ttl

Added versioning folder using new xapi.vocab.pub process

Versioning Update

---

dod-isd/dod-isd.jsonld

Resolves https://github.com/adlnet/xapi-authored-profiles/issues/48.

Remove multi-line JSON definitions

---

dod-isd/dod-isd.jsonld

We updated extension titles as well as corresponding guidance within verb definitions.

Update Capitalization per Reviewer Request

---

video/v1.0.1/video.jsonld
video/v1.0.1/video.ttl
video/v1.0.2/video.jsonld
video/v1.0.2/video.ttl
video/v1.0/video.jsonld
video/video.jsonld
video/video.ttl

Merge and commits from jhaag75

Merge from repo

---

acrossx/v1.0.1/acrossx.jsonld
acrossx/v1.0.1/acrossx.ttl
acrossx/v1.0/acrossx.jsonld
acrossx/v1.0/acrossx.ttl

updates to add extensions and versioning fix

Updated AcrossX

---

acrossx/v1.0.1/acrossx.jsonld
acrossx/v1.0.1/acrossx.ttl

Added inline schema update for time in ISO8601

Update across time extension

---

video/v1.0.2/video.jsonld
video/v1.0.2/video.ttl

- Added RFC 5646 for cc-lang
- Added length extension
- Added completion-threshold extension
- Updated statement templates to include length and completion threshold

updates to support 1.0.2 release

---

starter-template.jsonld

Fix to valid json

---

video/v1.0.3/video.jsonld
video/v1.0.3/video.ttl

length was designated as a result extension, but should be context

correction to length extension

---

acrossx/acrossx.jsonld
acrossx/v1.0.1/acrossx.jsonld
acrossx/v1.0/acrossx.jsonld
activity-streams/activity-streams.jsonld
audio/audio.jsonld
audio/v1.0/audio.jsonld
cmi5/cmi5.jsonld
cmi5/v1.0/cmi5.jsonld
flashcards/v0.1/flashcards.jsonld
gblxapi/gblxapi.jsonld
open-badges/open-badges.jsonld
scorm/scorm.jsonld
scorm/v1.0/scorm.jsonld
seriousgames/seriousgames.jsonld
seriousgames/v1.0/seriousgames.jsonld
starter-template.jsonld
tincan/tincan.jsonld
video/v1.0.1/video.jsonld
video/v1.0.2/video.jsonld
video/v1.0.3/video.jsonld
video/v1.0/video.jsonld
video/video.jsonld

Most of these profiles violate the spec data model in some way or another. This should fix all of them.

Fix various formatting errors

---

activity-streams/activity-streams.jsonld
cmi5/cmi5.jsonld
cmi5/v1.0/cmi5.jsonld
open-badges/open-badges.jsonld
video/v1.0.2/video.jsonld

This should be all of them @mpkliewer.

fixing syntax issues pointed out by Matthew

---

cmi5/cmi5.jsonld

Updated Profile Per cmi5 Meeting March 13, 2020 to accurately reflect portions of the cmi5 spec that map to an xAPI authored profile.
Some cmi5 spec requirements (such has conditional behavior) can not be expressed in terms of an xAPI authored profile and are explained in scope notes/descriptions where possible.
Deferred, patterns and templates until profile server design is finalized.

Updated Profile Per cmi5 Meeting March 13, 2020
